FROM node:12.16.1-alpine
MAINTAINER Marvin
ENV HOST 0.0.0.0
ENV MYSQL ''
ENV MYSQL_PASSWORD ''
ENV MYSQL_USER root
ENV MYSQL_DATABASE_NAME b_simple_user_center
ENV MYSQL_PORT 3306
ENV MONGODB ''
ENV MONGODB_PASSWORD ''
ENV MONGODB_USER ''
ENV MONGODB_DATABASE_NAME ''
ENV MONGODB_PORT ''
ENV MONGODB_AUTH_SOURCE ''
ENV REDIS 127.0.0.1:6379
ENV REDIS_NAME user_token
ENV REDIS_HOST 127.0.0.1
ENV REDIS_POST 6379
ENV KAfKA 127.0.0.1:19092
ENV RABBITMQ ''
RUN mkdir -p /app
COPY . /app
WORKDIR /app
EXPOSE 8881
RUN ls
CMD ["node", "/app/index.js", "MONGODB=$MONGODB MONGODB_AUTH_SOURCE=$MONGODB_AUTH_SOURCE MONGODB_PORT=$MONGODB_PORT MONGODB_DATABASE_NAME=$MONGODB_DATABASE_NAME MONGODB_USER=$MONGODB_USER MONGODB_PASSWORD=$MONGODB_PASSWORD KAfKA=$KAfKA REDIS_NAME=$REDIS_NAME REDIS_HOST=$REDIS_HOST REDIS_POST=$REDIS_POST MYSQL=$MYSQL MYSQL_USER=$MYSQL_USER MYSQL_PASSWORD=$MYSQL_PASSWORD MYSQL_PORT=$MYSQL_PORT MYSQL_DATABASE_NAME=$MYSQL_DATABASE_NAME REDIS=$REDIS"]
