serverConfig:
  connectMicroservice: 3001
  port: 8881
  tokenSetTimeOut: 7200
  globalPrefix: 'simple-user-center/v1.0'
mysqlConfig:
  host: ''
  userName: ''
  password: ''
  dataBaseName: 'b_simple_user_center'
  port: 7000
mongodbConfig:
  host: ''
  userName: ''
  port:
  dataBaseName: ''
  password: ''
  authSource: ''
redisConfig:
  name: 'user_token'
  url: ''
  host: ''
  port:
  password:
kafkaConfig:
  url: ''
  clientId: ''
  groupId: ''
rabbitMQConfig:
  url: ''
  name: ''
  queue: ''
emailConfig:
  authPass: ''
  fromUser: '"Marvin" <1970305447@qq.com>'
  user: ''
